#!/usr/bin/ksh
sqlplus -s / as sysdba <<EOF>salida.txt
set pages 0
set head off
set lines 200
set trimspool off
set feed off
SELECT 'INSTANCE_NAME='||INSTANCE_NAME||chr(10)||'HOST_NAME='||HOST_NAME||chr(10)||'STARTUP_TIME='||(STARTUP_TIME - TO_DATE('01-01-1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS')) * 24 * 60 * 60 * 1000||chr(10)||
'DAYS_RUNNING='||FLOOR(SYSDATE - STARTUP_TIME)||chr(10)||'INSTANCE_STATUS='||STATUS from v$instance
UNION 
SELECT 'LAST_PATCH_ACTION='||(CAST(ACTION_TIME AS DATE)  - TO_DATE('01-01-1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS')) * 24 * 60 * 60 * 1000||chr(10)||'DAYS_SINCE_LASTPATCH='||EXTRACT(DAY FROM (SYSTIMESTAMP - ACTION_TIME))||chr(10)||
'RDBMS_VERSION='||COMMENTS from registry$history where ACTION_TIME=(select max(ACTION_TIME) from registry$history)  
UNION
SELECT 'DB_SIZE='||BYTES from (
  select sum(bytes)/*1024/1024/1024*/ AS BYTES from (
    select BYTES from V_$LOG
    union all
    select BYTES from V_$DATAFILE
    union all
    select BYTES from V_$TEMPFILE
    union all
    select BLOCK_SIZE*(FILE_SIZE_BLKS+1) AS BYTES from v$controlfile
    )
)
UNION
SELECT 'OS_TYPE='||rtrim(substr(replace(banner,'TNS for ',''),1,instr(replace(banner,'TNS for ',''),':')-1))||chr(10)||'OS_VERSION='||dbms_utility.port_string from v$version where  banner like 'TNS for %'
UNION
SELECT 'DBVAULT='||VALUE from v$option where PARAMETER in ('Oracle Database Vault')
UNION
SELECT 'BACKUP_TYPE='||INPUT_TYPE||chr(10)||'BACKUP_START_TIME='||(START_TIME - TO_DATE('01-01-1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS')) * 24 * 60 * 60 * 1000||chr(10)||
'BACKUP_END_TIME='||(END_TIME - TO_DATE('01-01-1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS')) * 24 * 60 * 60 * 1000||chr(10)||'BACKUP_INPUT_BYTES='||INPUT_BYTES||chr(10)||'BACKUP_OUTPUT_BYTES='||OUTPUT_BYTES||chr(10)||
'BACKUP_COMPRESS_RATIO='||OUTPUT_BYTES/INPUT_BYTES||chr(10)||'BACKUP_STATUS='||STATUS||chr(10)||'BACKUP_ELAPSED_SECONDS='||ELAPSED_SECONDS||chr(10)||'BACKUP_INPUT_BYTES_PER_SEC='||INPUT_BYTES_PER_SEC||chr(10)||
'BACKUP_OUTPUT_BYTES_PER_SEC='||OUTPUT_BYTES_PER_SEC||chr(10)||'DAYS_SINCE_LAST_BACKUP='||FLOOR(SYSDATE - START_TIME) from V$RMAN_BACKUP_JOB_DETAILS
where INPUT_TYPE='DB FULL' and START_TIME=(select max(START_TIME) from V$RMAN_BACKUP_JOB_DETAILS where INPUT_TYPE='DB FULL' and STATUS<>'RUNNING')
UNION
SELECT 'DB_CREATION_TIME='||(CREATED - TO_DATE('01-01-1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS')) * 24 * 60 * 60 * 1000||chr(10)||
'DB_RESETLOGS_TIME='||(RESETLOGS_TIME - TO_DATE('01-01-1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS')) * 24 * 60 * 60 * 1000||chr(10)||
'DB_PRIOR_RESETLOGS_TIME='||nvl((PRIOR_RESETLOGS_TIME - TO_DATE('01-01-1970 00:00:00', 'DD-MM-YYYY HH24:MI:SS')) * 24 * 60 * 60 * 1000,0)||chr(10)||
'DB_LOG_MODE='||LOG_MODE||chr(10)||'DB_OPEN_MODE='||OPEN_MODE||chr(10)||
'DB_DATABASE_ROLE='||DATABASE_ROLE||chr(10)||'DATAGUARD_BROKER='||DATAGUARD_BROKER||chr(10)||'GUARD_STATUS='||GUARD_STATUS from v$database
UNION
SELECT 'CPU_COUNT='||VALUE FROM V$PARAMETER WHERE NAME='cpu_count'
UNION
SELECT 'SGA_MAX_SIZE='||VALUE FROM V$PARAMETER WHERE NAME='sga_max_size'
UNION
SELECT 'INVALID_OBJECTS='||COUNT(*) FROM obj$ WHERE status IN (4, 5, 6);
;
EOF
grep . salida.txt


SELECT 'INSTANCE_NAME='||INSTANCE_NAME||chr(10)||'HOST_NAME='||HOST_NAME||chr(10)||'STARTUP_TIME='||STARTUP_TIME||chr(10)||
'DAYS_RUNNING='||FLOOR(SYSDATE - STARTUP_TIME)||chr(10)||'INSTANCE_STATUS='||STATUS from v$instance
UNION 
SELECT 'LAST_PATCH_ACTION='||CAST(ACTION_TIME AS DATE)||chr(10)||'DAYS_SINCE_LASTPATCH='||EXTRACT(DAY FROM (SYSTIMESTAMP - ACTION_TIME))||chr(10)||
'RDBMS_VERSION='||COMMENTS from registry$history where ACTION_TIME=(select max(ACTION_TIME) from registry$history)  
UNION
SELECT 'DB_SIZE='||BYTES||'GB' from (
  select sum(bytes)/1024/1024/1024 AS BYTES from (
    select BYTES from V_$LOG
    union all
    select BYTES from V_$DATAFILE
    union all
    select BYTES from V_$TEMPFILE
    union all
    select BLOCK_SIZE*(FILE_SIZE_BLKS+1) AS BYTES from v$controlfile
    )
)
UNION
SELECT 'OS_TYPE='||rtrim(substr(replace(banner,'TNS for ',''),1,instr(replace(banner,'TNS for ',''),':')-1))||chr(10)||'OS_VERSION='||dbms_utility.port_string from v$version where  banner like 'TNS for %'
UNION
SELECT 'DBVAULT='||VALUE from v$option where PARAMETER in ('Oracle Database Vault')
UNION
SELECT 'BACKUP_TYPE='||INPUT_TYPE||chr(10)||'BACKUP_START_TIME='||START_TIME||chr(10)||
'BACKUP_END_TIME='||END_TIME||chr(10)||'BACKUP_INPUT_BYTES='||INPUT_BYTES||chr(10)||'BACKUP_OUTPUT_BYTES='||OUTPUT_BYTES||chr(10)||
'BACKUP_COMPRESS_RATIO='||OUTPUT_BYTES/INPUT_BYTES||chr(10)||'BACKUP_STATUS='||STATUS||chr(10)||'BACKUP_ELAPSED_SECONDS='||ELAPSED_SECONDS||chr(10)||'BACKUP_INPUT_BYTES_PER_SEC='||INPUT_BYTES_PER_SEC||chr(10)||
'BACKUP_OUTPUT_BYTES_PER_SEC='||OUTPUT_BYTES_PER_SEC||chr(10)||'DAYS_SINCE_LAST_BACKUP='||FLOOR(SYSDATE - START_TIME) from V$RMAN_BACKUP_JOB_DETAILS
where INPUT_TYPE='DB FULL' and START_TIME=(select max(START_TIME) from V$RMAN_BACKUP_JOB_DETAILS where INPUT_TYPE='DB FULL' and STATUS<>'RUNNING')
UNION
SELECT 'DB_CREATION_TIME='||CREATED||chr(10)||
'DB_RESETLOGS_TIME='||RESETLOGS_TIME||chr(10)||
'DB_PRIOR_RESETLOGS_TIME='||nvl(PRIOR_RESETLOGS_TIME,'01-JAN-1900')||chr(10)||
'DB_LOG_MODE='||LOG_MODE||chr(10)||'DB_OPEN_MODE='||OPEN_MODE||chr(10)||
'DB_DATABASE_ROLE='||DATABASE_ROLE||chr(10)||'DATAGUARD_BROKER='||DATAGUARD_BROKER||chr(10)||'GUARD_STATUS='||GUARD_STATUS from v$database
UNION
SELECT 'CPU_COUNT='||VALUE FROM V$PARAMETER WHERE NAME='cpu_count'
UNION
SELECT 'SGA_MAX_SIZE='||VALUE FROM V$PARAMETER WHERE NAME='sga_max_size'
UNION
SELECT 'INVALID_OBJECTS='||COUNT(*) FROM obj$ WHERE status IN (4, 5, 6);

