ALTER TABLE UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI RENAME TO BORRAME;

CREATE TABLE UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI
(
  ID                         NUMBER(9),
  FECHA_HORA                 DATE,
  SIC                        VARCHAR2(16 BYTE),
  CUENTA                     VARCHAR2(16 BYTE),
  NUMERO_PLASTICO            VARCHAR2(16 BYTE),
  PRODUCTO                   VARCHAR2(100 BYTE),
  DESCRI_PRODUCTO            VARCHAR2(100 BYTE),
  ID_TRANSACCION             NUMBER,
  CLAVE_TRANSACCION          VARCHAR2(8 BYTE),
  DESCR_CLAVE_TRANSACCION    VARCHAR2(100 BYTE),
  SISTEMA_FUENTE             VARCHAR2(100 BYTE),
  MONTO_TRANSACCION          VARCHAR2(100 BYTE),
  CLAVE_MONEDA               VARCHAR2(100 BYTE),
  DESCRI_MONEDA              VARCHAR2(100 BYTE),
  COMISION_TRANSACCION       VARCHAR2(100 BYTE),
  CLAVE_ESTATUS_TRANSACCION  VARCHAR2(1 BYTE),
  DESCR_ESTATUS_TRANSACCION  VARCHAR2(256 BYTE),
  CLAVE_TIPO_CONTACTO        VARCHAR2(100 BYTE)
)
TABLESPACE UG_IVRPLADM_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
PARTITION BY RANGE (FECHA_HORA)
INTERVAL(NUMTODSINTERVAL(7, 'DAY'))
( 
   PARTITION P0 VALUES LESS THAN (TO_DATE('1-11-2019', 'DD-MM-YYYY'))
)
;

insert into UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI select * from UG_IVRPLADM.BORRAME where trunc(FECHA_HORA)>'31-OCT-19';

CREATE UNIQUE INDEX UG_IVRPLADM.PK_BIT_REPORTE_TRANS_MI1 ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI
(FECHA_HORA,ID)
LOCAL
LOGGING
TABLESPACE UG_IVRPLADM_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX UG_IVRPLADM.UK_RPTTRANSACCION_FECHA1 ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI
(FECHA_HORA)
LOCAL
LOGGING
TABLESPACE UG_IVRPLADM_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX UG_IVRPLADM.UK_RPTTRANSACCION_IDTRANS1 ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI
(ID_TRANSACCION)
LOCAL
LOGGING
TABLESPACE UG_IVRPLADM_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX UG_IVRPLADM.UK_RPTTRANSACCION_NMROPTCO1 ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI
(NUMERO_PLASTICO)
LOCAL
LOGGING
TABLESPACE UG_IVRPLADM_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX UG_IVRPLADM.UK_RPTTRANSACCION_SIC1 ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI
(SIC)
LOCAL
LOGGING
TABLESPACE UG_IVRPLADM_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

GRANT SELECT ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO A3091252;

GRANT SELECT ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO A3885097;

GRANT SELECT ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO A8036242;

GRANT SELECT ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO A8041436;

GRANT SELECT ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO HBAAL701;

GRANT SELECT ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO HCAFA940;

GRANT SELECT ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO HGOCM890;

GRANT SELECT ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO HMEQC841;

GRANT SELECT ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO HSAFG811;

GRANT DELETE, INSERT, SELECT, UPDATE ON UG_IVRPLADM.BIT_REPORTE_TRANSACCIONES_MI TO UG_IVRPLAPP;

EXEC DBMS_STATS.gather_table_stats('UG_IVRPLADM','BIT_REPORTE_TRANSACCIONES_MI');

DROP TABLE UG_IVRPLADM.BORRAME cascade constraints purge;

